[WIP] 教員名でシラバスを検索するAPIの実装
gdsc-tmu/InfoLinkAPI pull request #33
Opened 2024-03-19 15:05 UTC by tenk-9

## 概要
教員名でシラバスを検索するAPIを実装するPRです．from #3 .

- created: 3/20 00:00
- 追記1@議論: 3/20 00:10
- **テスト**の加筆: 3/21 4:15
- パラメータの種類を修正: 3/21 4:15

## 変更点
- 実装したrouteを設定
  - mod: `main.go`
- 実装したAPIのドキュメントを追加
  - mod: `docs/docs.go`, `docs/swagger.json`, `docs/swagger.yaml`
- controllerの実装
  - add: `src/controllers/syllabus_teacher.go`
  - パラメータの部分一致で検索する
  - **姓名の間のスペースをどう扱いますか？** -> **議論**
- routerの実装
  - add: `src/routes/syllabus_teacher.go`
  - クエリパラメータで教員名を指定する．
  - `syllabus/teacher?name={name}`
- testの設置
  - add: `sec/routes/syllabus_teacher_test.go`

## 影響範囲
- `main.go`
  - routeを設定したため，変更がある．
  - 他の機能への影響は無し．
- `docs/*`
  - 教員名でシラバスを検索するrouteについて，documentを追加した．
  - 他の機能へ影響は無し．

## テスト
テストで検証するのは
1. 指定した名前の教員が担当する授業が返されること
2. 指定した名前の教員以外が担当する授業が返されないこと
3. 姓名の間のスペースの有無を吸収できていること
4. アルファベットの全角半角に対応できていること

の4点とした．

実施するテスト内容と対応する検証要素は次の通り．
- 異なる日本人教員2人について，それぞれの名前を指定したとき，対応するシラバスのみが返ってくること(1, 2)
- 似た名前の日本人教員2人について，検索パラメータの変更によって絞り込みが行われること(1, 2)
- 異なる外国人教員2人について，それぞれの名前を指定したとき，対応するシラバスのみが返ってくること(1, 2, 4)
- 存在しない教員について，結果が空になること(2)
- 姓名間のスペースを``, ` `, `　`と変え，絞り込みが行えること(3)
- 全角で名前を入力したとき，正常に検索が行えること(4)

## 議論
### 教員名の性と名の間のスペースをどう扱いますか？
DB内に格納されている教員名は，確か次のような規則だったはず．
- 日本人: 半角スペース区切りで`性 名`
  - `山口 拓生`
- それ以外: スペース無し`FirstSecond`
  - `TakuoYamaguchi`

このとき，教員名として
1. 姓名間のスペースが無いもの e.g. `山口拓生`
2. 姓名間が全角スペースのもの e.g. `山口　拓生`
3. 英語表記の名前で，スペースを含むもの e.g. `Takuo Yamaguchi`

等が来たとき，どうするべきでしょうか．
ケース2, 3についてはどうにかなりそうなのですが，ケース1は姓名の区切りが分からず，困っています．

追記1:
石池で`山口拓生`のケースを試したところ，ヒットしなかったので，おそらく`WHERE teacher=%{name}%`のような検索をしているような気がします．この実装で十分な気もします．

2024-03-19 17:02 UTC, Atotti commented on src/routes/syllabus_teacher.go
> +	router.GET("/syllabus/teacher/:name", syllabusController.GetSyllabusByTeacher)
[IMO] 学部絞り込みとは違って、どんな値でも入りうる検索内容をパスパラメータに取るのはかなり不自然な気がします。

検索クエリのようにユーザーが入力した動的な情報を扱う場合には、クエリストリング(GETのクエリパラメータ)を使用する方が柔軟性があり、一般的です。

2024-03-20 07:12 UTC, taniiicom commented
input: `谷知拓`
↓
**`SELECT * FROM テーブル名 WHERE 名前 LIKE '%谷%知%拓%';`**

これでどうでしょう??

go において, 多バイト文字の分割は以下のような感じでできます
```
package main

import "fmt"

func main() {
    name := "谷知拓"
    queryName := "%"
    for _, char := range str {
        queryName += fmt.Sprintf("%s%%", char)
    }
}
```

2024-03-20 07:31 UTC, taniiicom requested changes
上の案で実装してみた場合

2024-03-20 07:31 UTC, taniiicom commented on src/controllers/syllabus_teacher.go
> +	teacherName = "%" + teacherName + "%" //部分一致
```suggestion
	// `都立太郎` -> `%都%立%太%郎%`
	queryTeacherName := "%"
	for _, rune := range teacherName {
		if !IsWhiteSpace(rune) {
			queryTeacherName += fmt.Sprintf("%s%%", rune)
		}
	}
```

2024-03-20 07:31 UTC, taniiicom commented on src/controllers/syllabus_teacher.go
> +	"net/http"
```suggestion
	"net/http"
	"unicode"
```

2024-03-20 07:31 UTC, taniiicom commented on src/controllers/syllabus_teacher.go
> +
```suggestion
// rune が空白文字であれば true を返却
func IsWhiteSpace(r rune) bool {
	return unicode.IsSpace(r)
}
```

2024-03-20 08:15 UTC, Atotti commented
これって順序を保持した部分一致検索になってるのか。なるほど、よさそう。これなら不要にマッチするケースもあまり増え無さそうかな？

2024-03-20 09:20 UTC, taniiicom commented
名前たぶん長くても(アルファベットの場合で)20字程度なので, おそらくこれくらいならパフォーマンスにそんなに影響ないと思うけど, ちょっと様子見かも
実装が簡単でかつ検索もれがないのはこれかな
巻き込んでるケースがいくつか発生するけど, そこまで似た名前の人はいないだろうということで一旦mm

2024-03-20 09:40 UTC, tenk-9 commented
うおーこれ良いですね！ありがとうございます

2024-03-20 09:41 UTC, tenk-9 commented on src/routes/syllabus_teacher.go
> +	router.GET("/syllabus/teacher/:name", syllabusController.GetSyllabusByTeacher)
なるほど，分かりました！パスパラメータに変更します

2024-03-20 19:14 UTC, tenk-9 commented
testの追加までしました，確認お願いします．

2024-03-21 01:11 UTC, taniiicom approved these changes
ありがとうございます
いいと思います!

[nits]
- 自分が先に書いていたコードの時点で public にしちゃってたんですが, 多分外からは使わないので, private にしておきました
- 将来的には, `isWhiteSpace` よく使いそうな部品ではあるので, `util`, `lib` あたりに共通化してもいいかもしれないですね

2024-03-21 01:11 UTC, taniiicom commented on src/controllers/syllabus_teacher.go
> +func IsWhiteSpace(r rune) bool {
```suggestion
func isWhiteSpace(r rune) bool {
```

2024-03-21 01:11 UTC, taniiicom commented on src/controllers/syllabus_teacher.go
> +		if !IsWhiteSpace(r) {
```suggestion
		if !isWhiteSpace(r) {
```

2024-03-21 13:19 UTC, tenk-9 commented
確認ありがとうございます．
> （IsWhiteSpace -> isWhiteSpace）private にしておきました
ありがとうございます．付け焼刃Go知識なので，privateか否かとか以外にも理解が浅いところがあると思うので，指摘してくれると嬉しいです．

2024-03-21 13:20 UTC, merged

2024-03-21 13:20 UTC, tenk-9 commented
close #3 .